### ISSUE TITLE
Website unreachable

### ISSUE THREAD

**Issue by EinDev** [Banou26/banou.dev#18]
I am unable to access your website. It seems like the DNS records are not present:
![grafik](https://github.com/Banou26/banou.dev/assets/12981672/58fadf06-ae4f-41a6-8785-143a100db961)

**Comment by Banou26** [comment]
Hey,

That's on purpose, I haven't really spent any time making a website to put on there, someday(probably next year) I will but not right now, as i have other more important projects in the works

I'm curious how you ended up here though lol
